# -*- coding: utf-8 -*-
"""house price rent.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11cBhhePtNgXvkOVIwxCzmxnQgtIUy9of
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib.pyplot as plt
# %matplotlib inline

HouseDF = pd.read_csv('house price rent.csv')

HouseDF.head()

HouseDF.info()

HouseDF.describe()

HouseDF.columns

sns.pairplot(HouseDF)

sns.heatmap(HouseDF.corr(), annot=True)

X=HouseDF[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition']]

y=HouseDF['price']

from sklearn.model_selection import train_test_split

X_train , X_test, y_train, y_test=train_test_split(X,y,test_size=0.40,random_state=3)

X_train

from sklearn.linear_model import LinearRegression

lm=LinearRegression()

lm.fit(X_train,y_train)

coeff_df = pd.DataFrame(lm.coef_,X.columns,columns=['Coefficient'])

coeff_df

predictions = lm.predict(X_test)

plt.scatter(y_test,predictions)

sns.displot((y_test-predictions),bins=50);